# Generated by Django 3.0.6 on 2020-05-25 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_no', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
    ]
